# Generated by Django 4.2.10 on 2024-03-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_express", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="adminterritory",
            unique_together={("category", "official_id")},
        ),
    ]
